export const CLOSE_PULLOUT = 'CLOSE_PULLOUT';
export const RECEIVE_THING_LIST = 'RECEIVE_THING_LIST';
export const REQUEST_THING_LIST = 'REQUEST_THING_LIST';
export const RESIZE_BREAKPOINT = 'RESIZE_BREAKPOINT';
export const SET_THEME = 'SET_THEME';
export const TOGGLE_PULLOUT = 'TOGGLE_PULLOUT';
